### PR TITLE
Send files as a whole instead of slicing them up

### PR DESCRIPTION
**Pull request by DaveSchmid**
## Description

Solves the problem of truncated files sent to Browser.

## Motivation and Context

- Fixes nanoFramework/Home#1216

## How Has This Been Tested?

Tested with modified WebServer.Sample:
https://github.com/DaveSchmid/Samples/releases/tag/WebServer.Sample-Errors

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by josesimoes — COMMENTED** [review]
This fix requires that the target has enough free memory in managed heap in order to create a large enough byte array to store the file to be sent. Despite it works for small files or targets that have a large heap space, it won't work for targets that have a small managed heap.
That's the reason for using `MaxSizeBuffer` .

Any proposed fix for this issue has to take into account the above constrains.

**Comment by Ellerbach** [comment]
> Solves the problem of truncated files sent to Browser.

I don't have this issue and it's been proven to work perfectly. It's also a pattern used in all streams, so what you propose is not going to solve the problem as there is no real problem. Which browser are you using? Which file are you trying to transfer?

**Comment by DaveSchmid** [comment]
There is a real problem. Please see my detailed error analysis in the issue. The file is completely loaded into memory anyway. So it doesn't make any sense to slice it again. 
If you split it up, it has to be transferred correctly.
https://github.com/nanoframework/Home/issues/1216

**Comment by Ellerbach** [comment]
@DaveSchmid I'll close this PR as there is the other one fixing the root cause and this won't work for small devices. The chunk pattern is the right one. Thanks again for your help.

**Pull request closed without merging**
