### PR TITLE
Fix comments for Intellisense 

### PR DESCRIPTION
**Pull request by networkfusion**
## Motivation and Context
* The project file was missing `<Content Include="packages.lock.json" />`
* Add missing xml documentation.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by networkfusion** [comment]
Related to https://github.com/nanoframework/nanoframework.github.io/pull/139

**Review by Ellerbach — APPROVED** [review]
Looks good to me. We definitely should add the linter on more repositories!

**Review by josesimoes — COMMENTED** [review]
Always better to have the Intellisense comets there. 
To me, the thing with the ones here, is that they do not explain anything to the developer using them. They're are just repeating the name of the method... the warning will go away, sure, but nothing will become clearer by providing these...

**Comment by networkfusion** [comment]
> 

I guess this is a comprimise.
It is better to not have warnings, and as it stands, the project was inconsistant with the approach.
Surely this is also useful for the generated documentation?

Either way, let me know whether this can be merged so we can move on.

**Comment by Ellerbach** [comment]
@networkfusion this PR has conflict now. Either resolves them, either close the PR and reopen it. I was even thinking to add the linter on it. That would force to clean the comments as well.

**Pull request merged**
